name: release
on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet publish -o openphoto /p:Version="${{ github.event.release.tag_name }}"
      - uses: actions/upload-artifact@v2
        with:
          name: openphoto
          path: openphoto
